# ============================================
# Ansible Static Inventory — Personal Lab
# ============================================

# Control node
# ansible_connection=local prevents SSH from being used for localhost
#[control]
#localhost ansible_connection=local


# Web-server group
[web]
node1 ansible_host=192.168.1.154


# Application-server group
[app]
node2 ansible_host=192.168.1.185


# Database-server group
[db]
node3 ansible_host=192.168.1.190

# Parent group containing web and app
[application:children]
web
app

# Parent group containing all managed-node groups
[three_tier_app:children]
web
app
db

# if we have large number of hosts or series of IP addresses or complete subnet.
[database]
192.168.10.[50:70]

# if we have large number of hosts having hostname in a sequence.
[sandbox]
server[1:9].nitclasses.com



# Variables inherited by every inventory host
[all:vars]

# SSH user used to connect to managed nodes
ansible_user=ansibleadmin

# Python interpreter used to execute Ansible modules
ansible_python_interpreter=/usr/bin/python3

# Optional private SSH key
# Uncomment this only when the key must be specified explicitly
# ansible_ssh_private_key_file=/home/ansibleadmin/.ssh/id_ed25519


